base_url = "https://asus-linux.org"
title = "ROG Control Center - Control your ASUS laptop on Linux"
description = " asus-linux org"

compile_sass = false
minify_html = false
build_search_index = false

[markdown]
highlight_code = false